language: python

install:
  - pip install -r requirements.txt

matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true
script:
  - pytest
# command to run test coverage
after_success:
  - coveralls