language: python

matrix:
  include:
    - python: 2.7
    - python: 3.4
    - python: 3.5
    - python: 3.6
    - python: 3.7
      dist: xenial
      sudo: true

install:
  - pip install -r requirements.txt
  - pip install coveralls
  - pip install pytest-cov 

script:
  - pytest 
after_success:
  - coveralls
